[package]
name = "polycubes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = { optional = true, version = "0.17.5" }

[features]
default = ["indicatif"]
